### PR TITLE
Leaderboard: final touches

### PR DESCRIPTION
**Pull request by ridwanediallo**
# Project requirements: 

1️⃣ Now you should improve the look and feel of the application, adding the styles of your choice.
2️⃣ Please keep the general layout of the wireframe, this is the only mandatory requirement.
3️⃣ You can use plain CSS or any CSS framework, it's up to you.

### CODE REVIEW

**Comment by ridwanediallo** [comment]
Hello,
I would want to point out that I forgot to create a new branch and I pushed all the new implementations to the dev branch. I did know how to correct it. However, now I am creating the pull request on the dev branch.

**Review by keroloussamy — COMMENTED** [review]
Hi @ridwanediallo, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't follow the Gitflow correctly. You can use this [link](https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/) and to rename this branch and create another one the `dev` one and make it the default.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ridwanediallo** [comment]
Hello, 
After I have renamed the branch it closed my pull request. What should I do?

**Comment by keroloussamy** [comment]
Sorry, I didn't see it, but I think you solved it when we met on zoom.

**Pull request closed without merging**
